### ISSUE TITLE
Building for 32bit on Ubuntu

### ISSUE THREAD

**Issue by andia89** [bil-elmoussaoui/sni-qt#1]
I can build the package for 64bit without problems. I have no idea how to build it for 32bit though. For experimenting with teamviewer it is necessary to have 32bit packages. It works when uploading to the ppa, but this is not the best way to debug...

**Comment by bilelmoussaoui** [comment]
This does not help ? https://github.com/bil-elmoussaoui/Hardcode-Tray/wiki/How-to-build-sni-qt also check this for debugging https://github.com/bil-elmoussaoui/sni-qt#debug

**Comment by andia89** [comment]
Yeah debugginh seems to be already built in. No Chance it seems that multiarch doesnt really work on Ubuntu

**Comment by bilelmoussaoui** [comment]
@wa4557 it's one of the reasons i moved to Arch :p
