### ISSUE TITLE
PKGBUILD

### ISSUE THREAD

**Issue by Jacobtey** [bil-elmoussaoui/sni-qt#2]
Are you planning make PKGBUILD for Arch based systems?

**Comment by bilelmoussaoui** [comment]
Yeah :) https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/242; i'm just too busy with studies those days to give it a shout! I still don't know if i'm just going to extract the deb file from the launchpad ppa or build it from scratch..

**Comment by bilelmoussaoui** [comment]
@Jacobtey just to let you know that i'm going to create a build pretty soon ;) just need to test few things before we release anything

**Comment by Jacobtey** [comment]
@bil-elmoussaoui thank u

**Comment by bilelmoussaoui** [comment]
@Jacobtey Done, i will create stable releases once we have something working perfectly. The aur packages are [lib32-sni-qt-patched-git](https://aur.archlinux.org/packages/lib32-sni-qt-patched-git/) and [sni-qt-patched-git](https://aur.archlinux.org/packages/sni-qt-patched-git/)
