### ISSUE TITLE
sni-qt:i386 is uninstallable (dependencies with impossible requirements)

### ISSUE THREAD

**Issue by SolarLiner** [bil-elmoussaoui/sni-qt#8]
![image](https://user-images.githubusercontent.com/4302963/29256505-18b51ee8-80d5-11e7-902e-36690c599fa9.png)

Installing sni-qt and qni-qt:i386 as part of Hardcode-Tray's installation yeilds impossible to install dependencies.

**Comment by SolarLiner** [comment]
Hold on, this may be due to the Vietnamese mirrors I'm using.

**Comment by SolarLiner** [comment]
Confirmed as a mirror problem. Weird but not upstream. Sorry for the unnecessary notifications :/

**Comment by bilelmoussaoui** [comment]
Not a problem :)
